# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql2
  database: js_dev
  username: root
  password: root
  pool: 5
  timeout: 5000
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  database: js_test
  username: root
  password: root
  pool: 5
  timeout: 5000
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql2
  database: ygamretuta_js
  pool: 5
  host: localhost
  username: ygamretuta_js
  password: jinsei
  timeout: 5000
